services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - id_card_manager

  server:
    build: ./server
    ports:
      - 5100:5100
    depends_on:
      - mongodb
    networks:
      - id_card_manager
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/id_card_manager

  # client:
  #   build: ./client
  #   ports:
  #     - 9100:80
  #   networks:
  #     - id_card_manager
  #   environment:
  #     - VITE_APP_API_URL=http://localhost:5100

volumes:
  data:

networks:
  id_card_manager:
